### ISSUE TITLE
📃 게시글 기능 구현 📃

### ISSUE THREAD

**Issue by 1-blue** [1-blue/blegram#17]
# 📤 FE
- [x] 다중 이미지 입력받는 레이아웃 작성
- [x] 게시글 생성 페이지 작성
- [x] 게시글들 패치 로직 작성
- [x] 게시글들 렌더링 로직 작성 ( #19  )
- [x] 게시글 내용 초기에 한 줄만 렌더링
- [x] `recoil`을 이용한 전역 모달 ( #20 )
- [x] 게시글 삭제 로직 작성
- [x] 클립보드 ( [링크](https://kyounghwan01.github.io/blog/React/clipboard-copy/#%E1%84%89%E1%85%A5%E1%84%85%E1%85%A9%E1%86%AB) )
- [x] `react-slick` 이미지 캐루셀, `arrow`, `dot` 커스터마이징 ( #21 )

# 📥 BE
- [x] 게시글, 댓글, 북마크 모델 작성
- [x] 다중 이미지 입력받는 엔드포인트 작성
- [x] `prisma` 가짜 데이터 로직 작성
- [x] 게시글 생성 엔드포인트 작성
- [x] 게시글들 가져오기 엔드포인트 작성
- [x] 게시글 삭제 엔드포인트 작성

# 구현할 기능
- [ ] 게시글 수정 기능
- [ ] 사람 태그 기능
- [ ] 위치 등록
- [ ] 음악 등록
