### ISSUE TITLE
💙 게시글 좋아요 기능 구현 💙

### ISSUE THREAD

**Issue by 1-blue** [1-blue/blegram#28]
# 📤 FE
- [x] 좋아요 레이아웃
- [x] 좋아요 추가
- [x] 좋아요 제거
- [x] 좋아요 누른 유저 목록 보기 ( 전역 모달 #20 참고 )
- [x] 특정 게시글에 좋아요 누른 유저 무한 스크롤링 ( #19 참고 )
- [x] 좋아요 누른 유저들 보여주는 모달 외부 클릭 시 닫히는 기능 ( #20 참고 )
- [x] 좋아요 누른 유저들 보여주는 모달 열리면 외부 스크롤 금지 기능 ( #20 참고 )
- [x] 좋아요 누른 유저들 보여주는 모달 등장 애니메이션
- [x] 스켈레톤 UI

# 📥 BE
- [x] 좋아요 스키마 ( prisma )
- [x] 좋아요 추가
- [x] 좋아요 제거
- [x] 특정 게시글에 좋아요 누른 유저 부분적으로 불러오기

# 좋아요 누른 사람들 패치 로직 변경
## 이전 방식
1. 게시글을 요청할 때 총 좋아요 개수 얻기
2. 좋아요를 누른 사람들 모두의 최소 정보 얻기 ( `idx`, `name`, `nickname`, `avatar` )

## 수정 방식
1. 게시글을 요청할 때 총 좋아요 개수 얻기
2. 현재 로그인한 유저가 좋아요 눌렀는지에 대한 정보 얻기
3. 좋아요를 누른 유저들 조회 시 해당 유저들을 부분적으로 가져오기 ( 무한 스크롤링 )
